before_build:
  - cmd: dotnet --version
  - ps:  Get-ChildItem -Path "C:\Program Files\dotnet\sdk"
  - ps: scripts\patch_versions.ps1

branches:
  only:
    - master
    - dev

build_script:
  - ps: scripts\build.ps1

test: off

artifacts:
  - path: src\Armyknife\bin\release\netcoreapp2.0\win10-x64\publish\armyknife_*.exe
    name: armyknife-windows
    type: zip
  - path: docs
    name: docs
    type: zip

deploy:
  release: $(versionString)
  provider: GitHub
  auth_token:
    secure: Zcoti9GsS4Y1t12qVcWhfDXMJLW8QLt4SdeQi8VKUFBtd/gVyWsZlLXDOHLP8i5U
  artifact: /.**\.zip/
  draft: true
  on:
    branch: master