before_build:
  - cmd: dotnet --version
  - ps:  Get-ChildItem -Path "C:\Program Files\dotnet\sdk"
  - ps: scripts\patch_versions.ps1

environment:
  access_token:
    secure: Zcoti9GsS4Y1t12qVcWhfDXMJLW8QLt4SdeQi8VKUFBtd/gVyWsZlLXDOHLP8i5U
  COVERALLS_REPO_TOKEN:
    secure: XzMSOD/Z5rLyNTGAuUFDTolKl8oOjUboNrLliNQQb1V2chOvNtpVQVBDiBgC6VgZ

branches:
  only:
    - master
    - dev

build_script:
  - ps: scripts\build.ps1
  - ps: scripts\build_choco.ps1
  - cmd: %USERPROFILE%\.nuget\packages\coveralls.io\1.4.2\tools\coveralls.net.exe --opencover OpenCover.xml -r %COVERALLS_REPO_TOKEN%

test: off

artifacts:
  - path: src\Armyknife\bin\release\netcoreapp2.0\win10-x64\publish\armyknife_*.exe
    name: armyknife-windows
    type: zip
  - path: docs
    name: docs
    type: zip`
  - path: armyknife.*.nupkg
    name: armyknife-choco
    type: zip

deploy:
  release: $(versionString)
  provider: GitHub
  auth_token: $(access_token)
  draft: true
  on:
    branch: master

on_success:
  - cmd: git config --global credential.helper store
  - ps: Add-Content "$env:USERPROFILE\.git-credentials" "https://$($env:access_token):x-oauth-basic@github.com`n"
  - ps: git config --global user.email github@winterwerp.it
  - cmd: git config --global user.name "Duco"
  - cmd: git add *.csproj
  - cmd: git add docs/index.html
  - ps: git commit -m "[skip ci] Updated files for version $($env:versionString)"
  - cmd: git push origin HEAD:%APPVEYOR_REPO_BRANCH%