before_build:
  - cmd: dotnet --version
  - ps:  Get-ChildItem -Path "C:\Program Files\dotnet\sdk"
  - ps: scripts\patch_versions.ps1

environment:
  access_token:
    secure: Zcoti9GsS4Y1t12qVcWhfDXMJLW8QLt4SdeQi8VKUFBtd/gVyWsZlLXDOHLP8i5U
  git_email:
    secure: iJtd56dA1OpqZhduaPwoCA==
    

branches:
  only:
    - master
    - dev

build_script:
  - ps: scripts\build.ps1

test: off

artifacts:
  - path: src\Armyknife\bin\release\netcoreapp2.0\win10-x64\publish\armyknife_*.exe
    name: armyknife-windows
    type: zip
  - path: docs
    name: docs
    type: zip

deploy:
  release: $(versionString)
  provider: GitHub
  auth_token: $(access_token)
  draft: true
  on:
    branch: master

deploy_script:
  - cmd: git config --global credential.helper store
  - ps: Add-Content "$env:USERPROFILE.git-credentials" "https://$($env:access_token):x-oauth-basic@github.com`n"
  - cmd: git config --global user.email $($env:github_email)
  - cmd: git config --global user.name "Duco".
  - cmd: git push origin --delete gh-pages
  - cmd: git subtree push --prefix docs origin gh-pages