//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Armyknife.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ToolResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ToolResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Armyknife.Resources.ToolResources", typeof(ToolResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decodes a piece of Base64 encoded text..
        /// </summary>
        public static string Base64DecodeDescription {
            get {
                return ResourceManager.GetString("Base64DecodeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usage:
        ///- base64decode ZGVjb2RlIHRoaXM=
        ///- base64decode --input ZGVjb2RlIHRoaXM= --outputFile &quot;C:\tmp\output.txt&quot;
        ///- base64decode --inputFile &quot;C:\tmp\input.txt&quot; --outputFile &quot;C:\tmp\output.txt&quot;.
        /// </summary>
        public static string Base64DecodeHelp {
            get {
                return ResourceManager.GetString("Base64DecodeHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encodes a piece of text or a file to a Base64 string..
        /// </summary>
        public static string Base64EncodeDescription {
            get {
                return ResourceManager.GetString("Base64EncodeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usage:
        ///- base64encode encode this
        ///- base64encode --input encode this --outputFile &quot;C:\tmp\output.txt&quot;
        ///- base64encode --inputFile &quot;C:\tmp\input.txt&quot; --outputFile &quot;C:\tmp\output.txt&quot;.
        /// </summary>
        public static string Base64EncodeHelp {
            get {
                return ResourceManager.GetString("Base64EncodeHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encodes a piece of text to an MD5 hash..
        /// </summary>
        public static string Md5Description {
            get {
                return ResourceManager.GetString("Md5Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usage:
        ///- md5 hash this
        ///- md5 --input hash this --outputFile &quot;C:\tmp\output.txt&quot;
        ///- md5 --inputFile &quot;C:\tmp\input.txt&quot; --outputFile &quot;C:\tmp\output.txt&quot;
        ///- md5 --input hash this --hmac secret-key
        ///
        ///Optional properties:
        ///- hmac: the signature key for the MD5 hash
        ///- outputType: how the string should be generated (should be &apos;hex&apos; or &apos;base64&apos;).
        /// </summary>
        public static string Md5Help {
            get {
                return ResourceManager.GetString("Md5Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encodes a piece of text to a SHA1 hash..
        /// </summary>
        public static string Sha1Description {
            get {
                return ResourceManager.GetString("Sha1Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usage:
        ///- sha1 hash this
        ///- sha1 --input hash this --outputFile &quot;C:\tmp\output.txt&quot;
        ///- sha1 --inputFile &quot;C:\tmp\input.txt&quot; --outputFile &quot;C:\tmp\output.txt&quot;
        ///- sha1 --input hash this --hmac secret-key
        ///
        ///Optional properties:
        ///- hmac: the signature key for the MD5 hash
        ///- outputType: how the string should be generated (should be &apos;hex&apos; or &apos;base64&apos;).
        /// </summary>
        public static string Sha1Help {
            get {
                return ResourceManager.GetString("Sha1Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encodes a piece of text to a SHA256 hash..
        /// </summary>
        public static string Sha256Description {
            get {
                return ResourceManager.GetString("Sha256Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usage:
        ///- sha256 hash this
        ///- sha256 --input hash this --outputFile &quot;C:\tmp\output.txt&quot;
        ///- sha256 --inputFile &quot;C:\tmp\input.txt&quot; --outputFile &quot;C:\tmp\output.txt&quot;
        ///- sha256 --input hash this --hmac secret-key
        ///
        ///Optional properties:
        ///- hmac: the signature key for the SHA256 hash
        ///- outputType: how the string should be generated (should be &apos;hex&apos; or &apos;base64&apos;).
        /// </summary>
        public static string Sha256Help {
            get {
                return ResourceManager.GetString("Sha256Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encodes a piece of text to a SHA384 hash..
        /// </summary>
        public static string Sha384Description {
            get {
                return ResourceManager.GetString("Sha384Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usage:
        ///- sha384 hash this
        ///- sha384 --input hash this --outputFile &quot;C:\tmp\output.txt&quot;
        ///- sha384 --inputFile &quot;C:\tmp\input.txt&quot; --outputFile &quot;C:\tmp\output.txt&quot;
        ///- sha384 --input hash this --hmac secret-key
        ///
        ///Optional properties:
        ///- hmac: the signature key for the SHA384 hash
        ///- outputType: how the string should be generated (should be &apos;hex&apos; or &apos;base64&apos;).
        /// </summary>
        public static string Sha384Help {
            get {
                return ResourceManager.GetString("Sha384Help", resourceCulture);
            }
        }
    }
}
